codelord_i18n::init!();

pub mod about;
pub mod animation;
pub mod audio;
pub mod button;
pub mod codeshow;
pub mod color;
pub mod dialog;
pub mod drag_and_drop;
pub mod events;
pub mod file_picker;
pub mod git;
pub mod icon;
pub mod instruction;
pub mod keyboard;
pub mod language;
pub mod loading;
pub mod navigation;
pub mod page;
pub mod panel;
pub mod playground;
pub mod popup;
pub mod previews;
pub mod runtime;
pub mod search;
pub mod settings;
pub mod statusbar;
pub mod symbol;
pub mod tabbar;
pub mod terminal;
pub mod text_editor;
pub mod theme;
pub mod toast;
pub mod token;
pub mod ui;
pub mod voice;
pub mod xmb;

pub use bevy_ecs as ecs;
