//! Search state resource for ECS.
//!
//! Manages search query, options, matches, and navigation.

use bevy_ecs::prelude::Resource;

use std::ops::Range;
use std::sync::Arc;
use std::time::Instant;

/// Search state resource for the current search session.
#[derive(Resource)]
pub struct SearchState {
  // --- INPUTS (Modified by the UI) ---
  /// Current search query.
  pub query: String,
  /// Replace text (for find/replace).
  pub replace_text: String,
  /// Search options.
  pub case_sensitive: bool,
  pub regex_mode: bool,
  pub whole_word: bool,
  /// UI state.
  pub visible: bool,
  pub replace_mode: bool,
  /// Last time the search input was modified (for debouncing).
  pub last_input_time: Instant,

  // --- OUTPUTS (Generated by the Search System) ---
  /// Generation ID to track and discard stale results.
  pub generation: u64,
  /// Flat list of all match ranges (in bytes) - Arc for thread safety.
  pub matches: Arc<Vec<Range<usize>>>,
  /// Current match navigation index.
  pub current_match_index: usize,
  /// Total number of matches (convenience cache).
  pub total_matches: usize,
  /// Regex compilation error if any.
  pub regex_error: Option<String>,
}

impl SearchState {
  /// Creates a new [`SearchState`] instance.
  pub fn new() -> Self {
    Self {
      query: String::new(),
      replace_text: String::new(),
      case_sensitive: false,
      regex_mode: false,
      whole_word: false,
      visible: false,
      replace_mode: false,
      last_input_time: Instant::now(),
      generation: 0,
      matches: Arc::new(Vec::new()),
      current_match_index: 0,
      total_matches: 0,
      regex_error: None,
    }
  }

  /// Show the search panel.
  pub fn show(&mut self) {
    self.visible = true;
  }

  /// Hide the search panel.
  pub fn hide(&mut self) {
    self.visible = false;
  }

  /// Toggle search panel visibility.
  pub fn toggle(&mut self) {
    self.visible = !self.visible;
  }

  /// Enable replace mode.
  pub fn enable_replace_mode(&mut self) {
    self.replace_mode = true;
    self.visible = true;
  }

  /// Reset match navigation.
  pub fn reset_navigation(&mut self) {
    self.current_match_index = 0;
    self.total_matches = 0;
  }

  /// Update match count.
  pub fn update_matches(&mut self, total: usize) {
    self.total_matches = total;
    if total == 0 {
      self.current_match_index = 0;
    } else {
      self.current_match_index = self.current_match_index.min(total - 1);
    }
  }

  /// Navigate to next match.
  pub fn next_match(&mut self) {
    if self.total_matches > 0 {
      self.current_match_index =
        (self.current_match_index + 1) % self.total_matches;
    }
  }

  /// Navigate to previous match.
  pub fn previous_match(&mut self) {
    if self.total_matches > 0 {
      self.current_match_index = if self.current_match_index == 0 {
        self.total_matches - 1
      } else {
        self.current_match_index - 1
      };
    }
  }

  /// Update search query and track input time for debouncing.
  pub fn update_query(&mut self, query: String) {
    self.query = query;
    self.last_input_time = Instant::now();
    self.generation += 1;
  }

  /// Check if enough time has passed for debouncing.
  pub fn should_search(&self, debounce_ms: u64) -> bool {
    self.last_input_time.elapsed().as_millis() >= debounce_ms as u128
  }

  /// Update search results if generation matches.
  pub fn update_results(
    &mut self,
    generation: u64,
    matches: Arc<Vec<Range<usize>>>,
  ) -> bool {
    if generation == self.generation {
      self.matches = matches;
      self.total_matches = self.matches.len();
      self.current_match_index = self
        .current_match_index
        .min(self.total_matches.saturating_sub(1));
      true
    } else {
      false
    }
  }

  /// Toggle a search option.
  pub fn toggle_option(&mut self, option: SearchOption) {
    match option {
      SearchOption::CaseSensitive => {
        self.case_sensitive = !self.case_sensitive;
      }
      SearchOption::RegexMode => {
        self.regex_mode = !self.regex_mode;
      }
      SearchOption::WholeWord => {
        self.whole_word = !self.whole_word;
      }
    }
    // Trigger re-search
    self.generation += 1;
  }
}

impl Default for SearchState {
  fn default() -> Self {
    Self::new()
  }
}

/// Represents search option types for toggling.
#[derive(Debug, Clone, Copy)]
pub enum SearchOption {
  /// The case sensitive mode.
  CaseSensitive,
  /// The regular expression mode.
  RegexMode,
  /// The whole word mode.
  WholeWord,
}
